[project]
name = "fastapi-todos"
version = "0.1.0"
description = "Fastapi Todo Tracking Mock App"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "faker>=40.1.2",
    "fastapi[standard]>=0.128.1",
    "python-json-logger>=4.0.0",
    "semver>=3.0.4",
    "sqlmodel>=0.0.32",
]
